domain: specs.canonical.com

image: prod-comms.docker-registry.canonical.com/specs.canonical.com

env:
  - name: SENTRY_DSN
    value: https://e38013698989400884cce7bd9d862af3@sentry.is.canonical.com//51

  - name: PRIVATE_KEY_ID
    secretKeyRef:
      key: private-key-id
      name: google-private-key-id

  - name: PRIVATE_KEY
    secretKeyRef:
      key: private-key
      name: google-private-key

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'specs.canonical.com' ) {
      rewrite ^ https://specs.canonical.com$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
